backend/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = "apiApp"

# create router for backend api
apiRouter = routers.DefaultRouter()
apiRouter.register(r'users', views.UserViewSet)
apiRouter.register(r'groups', views.GroupViewSet)

# urls provided by the backend
urlpatterns = [
    path('api-auth/',
         include('rest_framework.urls', namespace='rest_framework')),
    path('', include(apiRouter.urls)),
]

backend/backend/urls.py
print(__name__)
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurantApp.urls', namespace='restaurantApp')),
    path('api/', include('api.urls', namespace='apiApp')),
]

backend/restaurantApp/urls.py
from django.urls import path, register_converter
import datetime
from restaurantApp import views
from scripts import functions

app_name = "restaurantApp"

class DateConverter:
    regex = '\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value


class TimeConverter:
    regex = '\d{2}:\d{2}:\d{2}'

    def to_python(self, value):
        time = functions.str_to_time_conversion(value)
        return time

    def to_url(self, value):
        return datetime.time.strftime(value, '%H:%M:%S')


register_converter(DateConverter, 'year')
register_converter(TimeConverter, 'time')

urlpatterns = [
    path("", views.index, name="index"),
    path("products/", views.product_list, name="products"),
    path('signin/', views.signin, name="signin"),
    path('logout/', views.user_logout, name="logout"),
    path('thx/', views.thx, name="thx"),
    path('controll_panel/', views.controll_panel, name="controll_panel"),
    path('controll_panel/create_user/', views.create_user, name="create_user"),
    path('controll_panel/check_user/', views.check_user, name="check_user"),
    path('controll_panel/new_product/<str:product_type>/', views.new_product, name="new_product"),

    path('manager_panel/', views.manager_panel, name="manager_panel"),
    path('manager_panel/create_restaurant', views.create_restaurant, name="create_restaurant"),

    path('products_group/edit_product/<int:id>/', views.edit_product, name="edit_product"),
    path('products_group/delete_product/<int:id>/', views.delete_product, name="delete_product"),
    path('products_group/', views.products_group, name="products_group"),
    path('products_group/<str:type>/', views.get_products, name="get_products"),

    path('manage_ingredients/<str:type>/', views.manage_ingredients, name="manage_ingredients"),
    path('manage_employees/restaurant/<int:id>/', views.manage_employees, name="manage_employees"),
    path('manage_employees/delete_employee/<int:id>/', views.delete_employee, name="delete_employee"),
    path('manage_employees/edit_employee/<int:id>/', views.edit_employee, name="edit_employee"),
    path('manage_employees/set_password/<int:id>/', views.employee_set_password, name="employee_set_password"),

    path('manage_restaurants/<str:type>/<int:id>/', views.manage_restaurants, name="manage_restaurants"),
    path('manage_restaurants/restaurant/add_ingredient_to_storage/<int:id>/', views.add_ingredient_to_storage,
         name="add_ingredient_to_storage"),
    path('manage_restaurants/restaurant/edit_ingredient_to_storage/<int:id>/', views.edit_ingredient_to_storage,
         name="edit_ingredient_to_storage"),

    path('manage_orders/', views.manage_orders, name="manage_orders"),

    path('raports/', views.raports, name="raports"),

    path('add_table/', views.add_table, name="add_table"),
    path('edit_table/<int:id>/', views.edit_table, name="edit_table"),
    path('delete_table/<int:id>/', views.delete_table, name="delete_table"),

    path('add_ingredient/', views.add_ingredient, name="add_ingredient"),
    path('delete_ingredient/<int:id>/', views.delete_ingredient, name="delete_ingredient"),

    path('new_order/', views.new_order, name="new_order"),

    path('active_orders/', views.active_orders, name="active_orders"),

    path('order/<int:id>/', views.order_detail, name='order_detail'),

    path('order/<int:id>/close/', views.close_order, name='close_order'),
    path('order/<int:id>/delete', views.delete_order, name='delete_order'),
    path('order/<int:id>/edit', views.edit_product_order, name='edit_product_order'),
    path('order/<int:id>/add_product/<str:type>/', views.order_add_product, name='order_add_product'),

    path('order/<int:id>/add_product/<int:product_id>', views.order_id_add_product_id,
         name='order_id_add_product_id'),

    path('reservation/<int:restaurant_id>/<year:reservation_date>/<time:time_start>/<time:time_end>/<int:table_id>/',
         views.client_form, name='client_form'),
    path('reservation/', views.reservation, name='reservation'),
]

backend/restaurantApp/forms.py
from django import forms
from models import *


class DateInput(forms.DateInput):
    input_type = 'date'

class DateForm(forms.Form):
    date_field = forms.DateField(widget=DateInput)

class ReservationForm(forms.ModelForm):
    # pass
    class Meta():
        model = Reservation
        fields = ['date', 'time_start', 'time_end']

        widgets = {
            'date': forms.DateInput(attrs={'type':'date'}),
            'time_start': forms.TimeInput(attrs={'type': 'time'}),
            'time_end': forms.TimeInput(attrs={'type': 'time'})
        }

backend/restaurantApp/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from restaurantApp.models import *
from scripts import functions


def manager_required(view_func):
    def _wrapped_view_func(request, *args, **kwargs):
        if request.user.employee.position != "M":
            return HttpResponse('Nie posiadasz uprawnień')
        else:
            return view_func(request, *args, **kwargs)

    return _wrapped_view_func


# Create your views here.


def index(request):
    return render(request, "restaurantApp/index.html", None)


def product_list(request):
    products = Product.objects.all()
    products_ingredients = ProductIngredient.objects.all()
    return_directory = {"products": products, "products_ingredients": products_ingredients}
    return render(request, "restaurantApp/products.html", context=return_directory)


@login_required
def special(request):
    return HttpResponse("You are logged in. Nice!")


@login_required
def user_logout(request):
    logout(request)
    return redirect('/')


def thx(request):
    return render(request, "restaurantApp/thx.html")


def signin(request):
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')
        remember_me = request.POST.get('remember_me')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                print(remember_me)
                if not remember_me:
                    request.session.set_expiry(0)
                    print("set expiry")
                return HttpResponseRedirect(reverse('restaurantApp:index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'restaurantApp/signin.html', {})


@login_required
def controll_panel(request):
    return render(request, "restaurantApp/controll_panel.html", None)


@login_required
@manager_required
def manager_panel(request):
    default_restaurant_id = request.user.employee.restaurant_id
    return render(request, "restaurantApp/manager_panel.html", {"restaurant_id": default_restaurant_id})


@login_required
def new_order(request):
    current_employee = request.user.employee
    order = Order.objects.create(employee=current_employee, date=datetime.datetime.now(), total_price=0, status='A')
    order.save()
    return redirect(f'/order/{order.id}')


@login_required
def active_orders(request):
    active_orders = Order.objects.filter(status='A')
    return render(request, "restaurantApp/active_orders.html", {"active_orders": active_orders})


def manage_orders(request):
    employee = request.user.employee
    active_employee_orders = Order.objects.filter(employee=employee, status="A")
    closed_employee_orders = Order.objects.filter(employee=employee, status="Z")
    return render(request, "restaurantApp/manage_orders.html",
                  {"active_orders": active_employee_orders, "closed_orders": closed_employee_orders})


@login_required
def order_detail(request, id):
    order_detail = Order.objects.get(id=id)
    products_order = ProductOrder.objects.filter(order_id=id)
    employee = request.user.employee
    active_employee_orders = Order.objects.filter(employee=employee, status="A")
    closed_employee_orders = Order.objects.filter(employee=employee, status="Z")
    return render(request, "restaurantApp/manage_orders.html",
                  {"order_detail": order_detail, "products_order": products_order,
                   "active_orders": active_employee_orders, "closed_orders": closed_employee_orders})


@login_required
def delete_order(request, id):
    Order.objects.get(id=id).delete()
    return redirect("/manage_orders/")


@login_required
def edit_product_order(request, id):
    product_order = ProductOrder.objects.get(id=id)
    if request.method == 'POST':
        quantity = int(request.POST.get('quantity'))
        print(type(quantity))
        if quantity == 0:
            product_order.delete()
        else:
            product_order.quantity = quantity
            product_order.save()
        return redirect(f'/order/{product_order.order.id}')
    else:
        return render(request, "restaurantApp/edit_product_order.html", {"product_order": product_order})


@login_required
def client_form(request, restaurant_id, reservation_date, time_start, time_end, table_id):
    if request.method == "POST":
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        table = Table.objects.get(id=table_id)
        if table.is_free(reservation_date, time_start, time_end):
            reservation = Reservation.objects.create(client_name=name, client_phone=phone, table=table,
                                                     date=reservation_date, time_start=time_start, time_end=time_end)
            reservation.save()
        return render(request, "restaurantApp/index.html")
    else:
        restaurant = Restaurant.objects.get(id=restaurant_id)
        table = Table.objects.get(id=table_id)
        print(reservation_date)
        print(type(time_start))
        return render(request, "restaurantApp/client_form.html",
                      {"restaurant": restaurant, "reservation_date": reservation_date, "time_start": time_start,
                       "time_end": time_end, "table": table})


@login_required
def products_group(request):
    # ingredient_types = IngredientType.objects.all()
    meals = Product.objects.filter(product_type='P')
    return render(request, "restaurantApp/manage_products.html", {"data": meals, "type": "meals"})


@login_required
def get_products(request, type="meals"):
    if type == "meals":
        meals = Product.objects.filter(product_type='P')
        return render(request, "restaurantApp/manage_products.html",
                      {"data": meals, "type": type})
    elif type == "beverages":
        beverages = Product.objects.filter(product_type='N')
        return render(request, "restaurantApp/manage_products.html",
                      {"data": beverages, "type": type})
    else:
        products = Product.objects.all()
        products_with_ingredient_type = []
        ingredient_type = type
        for product in products:
            if product.is_ingredient_type_in_product(ingredient_type):
                products_with_ingredient_type.append(product)
        return render(request, "restaurantApp/manage_products.html",
                      {"data": products_with_ingredient_type, "type": type})


@login_required
def order_add_product(request, id, type="meals"):
    if type == "meals":
        meals = Product.objects.filter(product_type='P')
        return render(request, "restaurantApp/order_add_product.html",
                      {"data": meals, "id": id, "type": type})
    elif type == "beverages":
        beverages = Product.objects.filter(product_type='N')
        return render(request, "restaurantApp/order_add_product.html",
                      {"data": beverages, "id": id, "type": type})
    else:
        products_with_ingredient_type = []
        ingredient_type = type
        products = Product.objects.all()
        for product in products:
            if product.is_ingredient_type_in_product(ingredient_type):
                products_with_ingredient_type.append(product)
        return render(request, "restaurantApp/order_add_product.html",
                      {"data": products_with_ingredient_type, "id": id, "type": type})


@login_required
def reservation(request):
    restaurants = Restaurant.objects.all()
    if request.method == "POST":
        restaurant_id = request.POST.get('restaurant')
        restaurant = Restaurant.objects.get(id=restaurant_id)
        date = request.POST.get('date')
        time_start = request.POST.get('time_start')
        time_start = functions.str_to_time_conversion(time_start)
        time_end = request.POST.get('time_end')
        time_end = functions.str_to_time_conversion(time_end)

        free_tables = []
        tables = Table.objects.filter(restaurant_id=restaurant_id)
        for table in tables:
            if table.is_free(date, time_start, time_end):
                free_tables.append(table)
        return render(request, "restaurantApp/reservation.html",
                      {"tables": free_tables, "restaurant": restaurant, "id": restaurant_id,
                       "reservation_date": date, "time_start": time_start, "time_end": time_end,
                       "restaurants": restaurants})

        # return render(request, "restaurantApp/reservation.html", {"restaurants":restaurants})

    return render(request, "restaurantApp/reservation.html", {"restaurants": restaurants})


@login_required
def new_product(request, product_type):
    ingredients = Ingredient.objects.all()
    if request.method == "POST":
        product_name = request.POST.get("product-name")
        product_price = float(request.POST.get("product-price"))
        # product_type = request.POST.get("product-type")
        product = Product.objects.create(name=product_name, price=product_price, product_type=product_type)
        product.save()

        for ing in ingredients:
            ing_id = request.POST.get(f"ID:{ing.name}")
            ing_quantity = request.POST.get(f"QUANTITY:{ing.name}")
            if ing_id != None:
                ingredient = Ingredient.objects.get(id=ing_id)

backend/templates/restaurantApp/edit_product_order.html
<!DOCTYPE html>
{% extends "restaurantApp/base.html" %}
{% load static %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/control_panel.css' %}">
{% endblock css_block %}

{% block body_block %}
    <div class="jumbotron">
        <h1>{{ product_order }}</h1>
        <form id="editProductOrderForm" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for id="quantity">Ilość: </label>
            <input id="quantity" name="quantity" type="number" value="{{ product_order.quantity }}" min="0">
            <button type="submit" class="btn btn-primary btn-lg"> Zapisz
            </button>
        </form>
    </div>
{% endblock %}

backend/templates/restaurantApp/manage_products.html
<!DOCTYPE html>
{% extends "restaurantApp/base.html" %}
{% load static %}
{% block css_block %}
    <link rel="stylesheet" href="{% static 'css/products_group.css' %}">
{% endblock %}
{% block body_block %}
    <div class="main-window">

        <div class="option-windows">
            <div id="accordion">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne"
                                    aria-expanded="true" aria-controls="collapseOne">
                                Kategorie
                            </button>
                        </h5>
                    </div>

                    {% if type == "meals" or type == "beverages" %}
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                             data-parent="#accordion">
                    {% else %}
                        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                    {% endif %}
                    <div class="card-body">
                        <ul class="list-group">
                            <li class="list-group-item"><a
                                    href="{% url "restaurantApp:get_products" "meals" %}">Posiłki</a>
                                <a href="{% url "restaurantApp:new_product" 'P' %}"><i
                                        class="addSign fas fa-plus-circle"></i></a>
                            </li>
                            <li class="list-group-item"><a
                                    href="{% url "restaurantApp:get_products" "beverages" %}">Napoje</a>
                                <a href="{% url "restaurantApp:new_product" 'N' %}"><i
                                        class="addSign fas fa-plus-circle"></i></a>
                            </li>
                        </ul>

                    </div>
                    </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingTwo">
                            <h5 class="mb-0">
                                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo"
                                        aria-expanded="false" aria-controls="collapseTwo">
                                    Rodzaj składnika
                                </button>
                            </h5>
                        </div>
                        {% if type == "meals" or type == "beverages" %}
                            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"
                                 data-parent="#accordion">
                        {% else %}
                            <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo"
                                 data-parent="#accordion">
                        {% endif %}

                        <div class="card-body">
                            <ul class="list-group">
                                <li class="list-group-item"><a
                                        href="{% url "restaurantApp:get_products" "S" %}">Ser</a>
                                </li>
                                <li class="list-group-item"><a
                                        href="{% url "restaurantApp:get_products" "W" %}">Warzywo</a>
                                </li>
                                <li class="list-group-item"><a
                                        href="{% url "restaurantApp:get_products" "M" %}">Mięso</a>
                                </li>

                            </ul>
                        </div>
                        </div>
                        </div>
                    </div>
                </div>
                <div class="view-window">

                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Produkt</th>
                            <th scope="col">Cena za sztukę</th>
                            <th class="right-align" scope="col">Opcje</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for product in data %}
                            <tr>
                                <td>{{ product.name }}</td>
                                <td>{{ product.price }} zł</td>
                                <td class="right-align">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-primary dropdown-toggle"
                                                data-toggle="dropdown"
                                                aria-haspopup="true" aria-expanded="false">
                                        </button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item"
                                               href="{% url "restaurantApp:edit_product" product.id %}">Edytuj
                                                produkt</a>
                                            <a class="dropdown-item"
                                               href="{% url "restaurantApp:delete_product" product.id %}">Usuń
                                                produkt</a>
                                        </div>
                                    </div>
                                </td>

                            </tr>
                            </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

backend/templates/restaurantApp/manage_restaurants.html
<!DOCTYPE html>
{% extends "restaurantApp/base.html" %}
{% load static %}
{% block css_block %}
    <link rel="stylesheet" href="{% static 'css/products_group.css' %}">
    <link rel="stylesheet" href="{% static 'css/control_panel.css' %}">
    <link rel="stylesheet" href="{% static 'css/accordion.css' %}">
{% endblock %}
{% block body_block %}


    <div class="main-window">

    <div class="option-windows">

    <div id="accordion">
        <div class="card">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne"
                            aria-expanded="true" aria-controls="collapseOne">
                        Magazyny
                    </button>
                    <a href="{% url "restaurantApp:create_restaurant" %}"><i
                            class="addSign fas fa-plus-circle"></i></a>
                </h5>
            </div>
            {% if storage %}
                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
            {% else %}
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            {% endif %}
            <div class="card-body">
                <ul class="list-group">
                    {% for restuarant in restaurants %}
                        <li class="list-group-item">
                            <a href="{% url "restaurantApp:manage_restaurants" "M" restuarant.id %}">{{ restuarant }}</a>
                        </li>
                    {% endfor %}
                </ul>

            </div>
            </div>
            </div>

            <div class="card">
                <div class="card-header" id="headingTwo">
                    <h5 class="mb-0">
                        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseTwo"
                                aria-expanded="true" aria-controls="collapseOne">
                            <a href="{% url "restaurantApp:add_table" %}"><i
                                    class="addSign fas fa-plus-circle"></i></a>
                            Stoliki
                        </button>
                    </h5>
                </div>
                {% if tables %}
                    <div id="collapseTwo" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                {% else %}
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                {% endif %}
                <div class="card-body">
                    <ul class="list-group">
                        {% for restuarant in restaurants %}
                            <li class="list-group-item">
                                <a href="{% url "restaurantApp:manage_restaurants" "S" restuarant.id %}">{{ restuarant }}</a>
                            </li>
                        {% endfor %}
                    </ul>

                </div>
                </div>
                </div>
            </div>
        </div>

        <div class="view-window">
            {% if storage %}
                <h3 class="table-header">Magazyn składników restauracji: {{ restaurant }}</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Składnik</th>
                        <th scope="col">Ilość na stanie</th>
                        <th  class="right-align" scope="col">Opcje</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for element in storage %}
                        <tr>
                            <td>{{ element.ingredient.name }}</td>
                            <td>{{ element.quantity }} {{ element.ingredient.quantity_type }}</td>
                            <td class="right-align">

                                <div class="btn-group">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                                            aria-haspopup="true" aria-expanded="false"></button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item"
                                           href="{% url "restaurantApp:add_ingredient_to_storage" element.id %}">Dodaj
                                            wartość do magazynu
                                        </a>
                                        <a class="dropdown-item"
                                           href="{% url "restaurantApp:edit_ingredient_to_storage" element.id %}">Nadpisz
                                            aktualny stan
                                        </a>

                                    </div>
                                </div>

                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% elif tables %}
                <h3 class="table-header">Stoliki restauracji: {{ restaurant }}</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Numer stolika</th>
                        <th scope="col">Ilość osób</th>
                        <th class="right-align" scope="col">Opcje</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for table in tables %}
                        <tr>
                            <td>{{ table.table_number }}</td>
                            <td>{{ table.chairs_quantity }}</td>
                            <td class="right-align">

                                <div class="btn-group">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                                            aria-haspopup="true" aria-expanded="false"></button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item"
                                           href="{% url "restaurantApp:edit_table" table.id %}">Edytuj stolik
                                        </a>
                                        <a class="dropdown-item"
                                           href="{% url "restaurantApp:delete_table" table.id %}">Usuń stolik
                                        </a>

                                    </div>
                                </div>

                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $("#new-ingredient").click(function () {
            if ($(".middle-absolute-div").css("display") == "none") {
                $(".middle-absolute-div").css("display", "block")
            } else {
                $(".middle-absolute-div").css("display", "none")
            }
        })
        $(".close-btn").click(function () {
            $(".middle-absolute-div").css("display", "none")
        })

    </script>
{% endblock %}

backend/templates/restaurantApp/manager_panel.html
<!DOCTYPE html>
{% extends "restaurantApp/base.html" %}
{% load static %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/control_panel.css' %}">
{% endblock css_block %}

{% block body_block %}
    <div class="jumbotron transparent">
        <table class="center control-panel">
            <tr>
                <td>
                    <button type="button" class="btn btn-primary btn-lg"
                            onclick="location.href='{% url 'restaurantApp:manage_employees' 0 %}'">Zarządzaj
                        pracownikami
                    </button>
                </td>

                <td>
                    <button type="button" class="btn btn-primary btn-lg"
                            onclick="location.href='{% url 'restaurantApp:manage_restaurants' "M" restaurant_id %}'">
                        Zarządzaj restauracjami
                    </button>
                </td>
                <td>
                    <button type="button" class="btn btn-primary btn-lg"
                            onclick="location.href='{% url 'restaurantApp:products_group' %}'">Zarządzaj
                        produktami
                    </button>
                </td>

            </tr>

            <tr>
                <td>
                    <button type="button" class="btn btn-primary btn-lg"
                            onclick="location.href='{% url "restaurantApp:manage_ingredients" "all" %}'">Zarządzaj
                        składnikami
                    </button>
                </td>
                <td>
                    <button type="button" class="btn btn-primary btn-lg"
                            onclick="location.href='{% url "restaurantApp:raports" %}'">Raporty

                    </button>
                </td>
                <td>
                    <button type="button" class="btn btn-warning btn-lg"
                            onclick="location.href='{% url 'restaurantApp:index' %}'">Wróć
                    </button>
                </td>


            </tr>

        </table>
    </div>
{% endblock %}